// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var textbox;
    textbox = document.getElementById("textbox");
    return textbox.appendChild(document.createTextNode("Time for coffee!"));
  };

}).call(this);
