// Generated by CoffeeScript 1.7.1
(function() {
  var Carousel, Mo, Rotator, TextToScreenApp,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TextToScreenApp = (function() {
    function TextToScreenApp(options) {
      var defaults;
      options = options || {};
      defaults = {
        base_url: '/displays',
        broken_image_src: '',
        campaign_id: '55555',
        image_page_no: 1,
        image_target: '#target',
        instagram_image_src: '',
        jsonp_url: 'http://localhost:3000/displays',
        logo_image_target: '',
        max_message_length: 35,
        message_end_string: '...',
        message_page_no: 1,
        message_text_target: '#target',
        mo_interval: 10000,
        phone_image_src: '',
        twitter_image_src: ''
      };
      $.extend(defaults, options);
      this.base_url = defaults.base_url;
      this.campaign_id = defaults.campaign_id;
      this.image_page_no = defaults.image_page_no;
      this.image_target = defaults.image_target;
      this.jsonp_url = defaults.jsonp_url;
      this.max_message_length = defaults.max_message_length;
      this.message_page_no = defaults.message_page_no;
      this.message_text_target = defaults.message_text_target;
      this.mo_interval = defaults.mo_interval;
      this.default_carousel_options = {
        mo_interval: this.mo_interval,
        message_text_target: this.message_text_target,
        image_target: this.image_target
      };
      if (typeof defaults.carousel === 'undefined') {
        this.carousel = new Carousel(this.default_carousel_options);
      } else {
        this.carousel = defaults.carousel;
      }
    }

    return TextToScreenApp;

  })();

  Mo = (function() {
    function Mo(obj) {
      this.preload_image = __bind(this.preload_image, this);
      this.content_url = obj.content_url;
      this.handle = obj.handle;
      this.id = obj.id;
      this.is_type = obj.is_type;
      this.message = obj.message;
      this.brk_src = 'http://www.catholictradition.org/Christ/merciful-jesus.jpg';
      this.image = null;
    }

    Mo.prototype.preload_image = function(arr, brkn_src) {
      var imageloadpost, item, loadedimages, newimages, ni, postaction, result;
      newimages = [];
      loadedimages = 0;
      postaction = function() {};
      arr = arr != null ? arr : this.brk_src;
      arr = typeof arr === 'object' ? arr : [arr];
      imageloadpost = function() {
        loadedimages++;
        if (loadedimages === arr.length) {
          return postaction(newimages);
        }
      };
      newimages = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arr.length; _i < _len; _i++) {
          item = arr[_i];
          ni = new Image;
          ni.src = item;
          ni.onload = function() {
            return imageloadpost();
          };
          ni.onerror = function() {
            return this.src = brkn_src;
          };
          ni.onabort = function() {};
          this.image = ni;
          $(ni).on('click', function() {
            return alert('it worked');
          });
          _results.push(ni);
        }
        return _results;
      }).call(this);
      result = {
        done: function(f) {
          return postaction = f || postaction();
        }
      };
      return result;
    };

    return Mo;

  })();

  Rotator = (function() {
    function Rotator() {}

    return Rotator;

  })();

  Carousel = (function() {
    function Carousel(options) {
      this.rotate_mos = __bind(this.rotate_mos, this);
      this.set_mos = __bind(this.set_mos, this);
      options = options || {};
      this.image_target = options.image_target;
      this.mo_interval = options.mo_interval;
      this.message_text_target = options.message_text_target;
      this.mos = [];
    }

    Carousel.prototype.set_mos = function(arr) {
      var a, tmp_arr;
      tmp_arr = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arr.length; _i < _len; _i++) {
          a = arr[_i];
          _results.push(new Mo(a));
        }
        return _results;
      })();
      return Array.prototype.push.apply(this.mos, tmp_arr);
    };

    Carousel.prototype.rotate_mos = function() {
      var counter, handle, interval, it, mos, tt;
      mos = this.mos;
      it = this.image_target;
      tt = this.message_text_target;
      interval = this.mo_interval;
      console.log("this is the interval: ", interval);
      counter = 0;
      $(it).html(mos[counter].image);
      $(tt).html(mos[counter].message);
      return handle = setInterval(function() {
        counter++;
        if (counter > mos.length) {
          return clearInterval(handle);
        } else {
          $(it).html(mos[counter].image);
          return $(tt).html(mos[counter].message);
        }
      }, interval);
    };

    return Carousel;

  })();

  $(function() {
    var form, parmas;
    form = $('form#login');
    window.tts = function() {
      var options;
      options = {
        image_target: '#picture-div',
        message_text_target: '#text-div',
        mo_interval: 10000
      };
      return new TextToScreenApp(options);
    };
    window.textToScreen = tts();
    parmas = {
      campaign_id: 23900
    };
    return form.submit(function(event) {
      event.preventDefault();
      return $.ajax({
        url: 'http://localhost:3000/displays',
        type: 'GET',
        data: parmas,
        crossDomain: true
      }).done(function(data) {
        var mo, _i, _len, _ref;
        console.log('awesome sauce! we are done!');
        window.textToScreen.carousel.set_mos(data.mos);
        _ref = window.textToScreen.carousel.mos;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          mo = _ref[_i];
          mo.preload_image(mo.content_url, 'http://www.catholictradition.org/Christ/merciful-jesus.jpg').done(function(images) {});
        }
        return window.textToScreen.carousel.rotate_mos();
      });
    });
  });

}).call(this);
